#+TITLE: 1 Pot Lentil Dal
#+DATE: 2019-02-07
#+SETUPFILE: recipe.setup

[[https://minimalistbaker.com/1-pot-lentil-dal/][Original link]]

* Ingredients
  - Rice
  - 2 Tbsp (30 g) coconut oil*
  - optional: 1 small green chili
  - 1 Tbsp (3 g) minced fresh ginger
  - 1 shallot, thinly sliced
  - 3 cloves garlic, minced (1.5 Tbsp or 9 g)
  - 4 Tbsp (60 g) Green Curry Paste (DIY or store-bought)
  - 2 1/4 cups (540 ml) light coconut milk* (canned is best)
  - 1 tsp ground turmeric
  - 1 tsp curry powder (store-bought or DIY)
  - Pinch each sea salt + black pepper
  - 1 cup (192 g) green lentils*, well rinsed and drained
  - 1 tsp coconut aminos or tamari (or soy sauce if not GF)
  - 1-2 Tbsp (12-24 g) coconut sugar or maple syrup (or other sweetener to taste)
  - 2 Tbsp (30 ml) fresh lemon juice
  - optional: pinch cayenne pepper (for more heat), cilantro and lemon/lime wedges

* Method
  1. Set rice cooking
  2. Heat a large pot over medium heat. Once hot, add coconut oil, green chili (optional), ginger, shallot, and garlic. Saute for 3-4 minutes, stirring occasionally. Reduce heat if browning too quickly.
  3. Add curry paste and stir to coat. Saute for another 2-3 minutes. Then add coconut milk, turmeric, curry powder, salt, and pepper. Stir to combine.
  4. Bring to a simmer over medium heat. Once simmering, add the lentils, coconut aminos (or tamari), coconut sugar (or maple syrup), and lemon juice and stir.
  5. Bring the mixture back to a simmer, and then reduce heat to low or medium-low and continue gently simmering for 15-20 minutes or until lentils are tender.
  6. Once the lentils are tender, taste and adjust flavor as needed, adding more lemon juice for acidity, a pinch of cayenne for heat (optional), curry powder or paste for more intense curry flavor, salt for saltiness, or coconut sugar or maple syrup for sweetness. The curry should be equally tangy and salty with a hint of sweetness and spice.
  7. Serve the dal as is or over rice of choice (I love white or brown rice, but it's also delicious over cauliflower rice). Garnish with lemon or lime wedges and cilantro (optional).
  8. Store leftovers in the refrigerator up to 4-5 days or in the freezer for 1 month.
