#+TITLE: Almond butter tofu stir-fry
#+DATE: 2019-05-30
#+SETUPFILE: recipe.setup

[[https://minimalistbaker.com/almond-butter-tofu-stir-fry/][Original link]]

* Ingredients
** Tofu
   - 340 g package extra firm tofu

** Marinade
   - 2 Tbsp sesame oil (divided)
   - 4 Tbsp reduced-sodium tamari (or soy sauce if not GF)
   - 3 Tbsp maple syrup
   - 2 Tbsp almond butter (or sub peanut butter)
   - 2 Tbsp lime juice
   - 1-2 tsp chili garlic sauce (or 1/2 tsp red pepper flake)

** Veggies
   - 453 g green beans (trimmed)
   - 2-3 small spicy peppers (I used cherry bomb - use bell peppers for less heat)

** Serving (optional)
   - Brown rice, white rice, or Cauliflower Rice

* Method
  1. Preheat oven to 200\deg{}C and line a baking sheet with parchment paper. Also
     wrap tofu in a clean, absorbent towel and set something heavy on top - like
     a cast-iron skillet - to press out excess moisture.
  2. Once oven is preheated, unwrap tofu and cut into small cubes. Arrange on
     the lined baking sheet in an even layer and bake for 25-30 minutes or until
     puffy, dried out, and slightly crispy on the edges (see photo). This step
     helps crisp up the tofu. The longer you bake it, the firmer and crispier it
     will get, so adjust cooking time accordingly.
  3. In the meantime, to a small mixing bowl, add half of the sesame oil (1 Tbsp
     as original recipe is written // adjust if altering batch size), tamari,
     maple syrup, almond butter, lime juice, and chili garlic sauce/red pepper
     flake/Thai chilies. Whisk to combine. Then taste and adjust flavor as
     needed, adding more almond butter for creaminess / nuttiness, tamari for
     saltiness, lime juice for acidity, or chili garlic sauce for heat. Set
     aside.
  4. If serving with rice, prepare at this time (see notes).
  5. Add baked tofu to the almond butter-tamari sauce and let marinate for 5
     minutes, stirring occasionally. The longer it marinates, the more intense
     the flavor, but I find 5-10 minutes to be sufficient.
  6. Heat a large skillet over medium heat. Once hot, add the tofu, leaving most
     of the marinade behind (this will be added to the vegetables for flavor).
  7. Cook for about 5 minutes, stirring occasionally, until browned on all sides
     and slightly caramelized. Remove from pan and set aside.
  8. To the skillet, add remaining sesame oil (1 Tbsp as original recipe is
     written / adjust if altering batch size), green beans and peppers and 2-3
     Tbsp (30-45 ml / amount as original recipe is written / adjust if altering
     batch size) of the marinade. Cover to steam for about 4-5 minutes or until
     green beans are slightly tender. Then remove lid, increase heat to medium
     high, and add remaining marinade and the tofu. Cook for an additional 1-2
     minutes, stirring frequently. Then remove from heat.
  9. Serve as is or over cooked rice or cauliflower rice. For more heat, serve
     with chili garlic sauce or Sriracha.
  10. Best when fresh. Store leftovers in the refrigerator up to 3 days. Reheat
      on the stovetop or in the microwave until hot.
