#+TITLE: Baked Vegan Cheesecake
#+DATE: 2023-08-18
#+SETUPFILE: recipe.setup

[[https://www.frei-style.com/en/the-perfect-vegan-cheesecake-with-silken-tofu][Original link]]

* Ingredients
** Cake base
- 260 gr 2 cups flour
- 80 gr 1/3 cup sugar (i.e. cane sugar)
- 2 tsp baking powder
- 1 Tbsp soy flour
- 140 gr vegan butter /margarine

** Cheese cream
- 800 gr 28 oz. Taifun silken tofu
- 150 gr 3/4 cup cane sugar
- 60-70 gr 1/2 cup starch
- Pulp of 2-3 vanilla beans or 4 tsp vanilla extract
- Zest of 1 organic lemon
- Juice of 1 lemon
- 70 ml 1/3 cup canola oil
- 2 Tbsp soy flour

* Instructions
** Cake base:
1. Mix flour, sugar, baking powder and soy flour
1. Add cold butter/margarine
1. Knead into a smooth dough – wrap it in foil and place it in fridge for approx. 30 minutes

** Cheese cream

1. Add the silken tofu along with all other ingredients into a mixer/food processor and mix on high level until the mixture is smooth, there shouldn’t be any chunks left
1. The more starch you use, the more solid the cheese cream gets

** Bake
1. Preheat the oven to 180°C
1. Take the cake base out of the fridge
1. Either grease a large springform pan ø 26 cm (10”) or two small ones ø 18 cm (7“) or line them with baking paper
1. Put the dough into the pan and press it down firmly as well as 2/3 from the sides
1. Put the cheese cream onto it
1. Bake the small pans for approx. 30-40 minutes, the large one for approx. 45-55 minutes
1. If you bake the golden drop cake with meringue, put the meringue onto the cake for the last 20 minutes and bake it
1. Let the cake cool off and take the cake out of the pan
