#+TITLE: Banana pancakes
#+DATE: 2025-04-25
#+SETUPFILE: recipe.setup

[[https://www.yummytoddlerfood.com/vegan-banana-pancakes/][Original link]]

* Ingredients
- 1 cup sliced very ripe banana (about 2 bananas)
- 1 cup plain flour (or buckwheat or whole wheat)
- 2 tablespoons ground flaxseed
- 2 teaspoons baking powder
- 1 teaspoon cinnamon
- 1/4 teaspoon salt
- 1 cup nondairy milk
- 2 tablespoons canola oil or melted coconut oil
- 1 teaspoon vanilla extract

* Instructions
1. Mash the banana very smooth with a fork.
2. Stir together the flour, flaxseed, baking powder, cinnamon, and salt in a medium bowl.
3. Stir in the banana, milk, oil, and vanilla. Gently combine to make a uniform, thick batter.
4. Heat a cast-iron or nonstick skillet or griddle over medium heat. Coat with neutral oil. Spoon out ¼ cup of the batter at a time, or less to make smaller pancakes, and spread to an even thickness about 1/2 inch thick. (Add a few slices of banana on top of each if desired.) Let cook about 3 minutes or until the edges are set.
5. Carefully flip and cook for another 1-2 minutes.
6. Serve immediately and repeat with the rest of the batter.
7. Serve with maple syrup, sliced banana, or other desired topping.
