#+TITLE: Chickpea Curry
#+DATE: 2020-05-09
#+SETUPFILE: recipe.setup

[[https://www.avantgardevegan.com/recipes/chickpea-curry/][Original link]]

* Ingredients
** Curry
   - 1 Onion, chopped small
   - 3 cloves Garlic, minced
   - 1 Hot Red Chilli, chopped fine
   - Thumb sized piece Ginger, minced
   - 3 tsp Sea Salt
   - 1 tsp Ground Turmeric
   - 1 tsp Mustard Seeds
   - 1 tsp Ground Coriander
   - 1 tsp Ground Cumin
   - 4 Curry Leaves
   - 1 tsp Ground Fenugreek
   - 2 tbs Tomato Puree
   - 2 cans Chickpeas, drained
   - 1 can Coconut Milk
   - 1 tbs Coconut Flour

** Rice
   - 1 cup/200g Basmati Rice
   - 2 cups/480ml Water
   - 1/2 tsp Ground Turmeric
   - 1 stick Cinnamon

** Garnish
   - Fresh Coriander
   - 1 tbs Black Onion Seeds
   - Mango Chutney
   - Poppadoms

* Method
  1. Place a large saucepan over a medium heat and add the oil. When the pan is hot add the onion, garlic, chilli & ginger, cook for 10 minutes – stirring often. This is the most important part of making the curry, getting your base ingredients lovely and golden will insure the finished curry has a powerful flavour.
  2. Add the all the spices & cook whilst stirring for another 3-4 minutes to let the spices roast & release their aromatics. Throw in the tomato puree and cook for 1 more minute before adding the chickpeas & stir well so they are coated in all the beautiful flavours.
  3. Deglaze the pan with the coconut milk and stir well then allow it to come to a simmer.
  4. Let your curry bubble away gently for around 12 minutes.
  5. Meanwhile, add the rinsed rice, water, turmeric & cinnamon stick to a small saucepan, pop the lid on and place the pan over a low heat to cook gently for around 12 minutes or until the liquid has been absorbed by the rice and it’s perfectly cooked.
  6. When the rice is cooked, just before serving stir the coconut flour into the curry to thicken it up.
  7. Serve up your curry with the rice, chutney, side salad, a sprinkle of black onion seeds and poppadoms.
