#+TITLE: Coconut Bacon
#+DATE: 2020-08-31
#+SETUPFILE: recipe.setup

[[https://www.connoisseurusveg.com/coconut-bacon/#wprm-recipe-container-12495][Original link]]

* Ingredients
- 1 1/2 cups unsweetened flaked coconut
- 1 tablespoons soy sauce or tamari
- 2 teaspoons liquid smoke
- 2 teaspoons maple syrup
- 2 teaspoons apple cider vinegar

* Instructions
1. Preheat oven to 160\deg{}C. 
2. Line a baking sheet with parchment paper.
3. In a medium-sized bowl, stir together the soy sauce or tamari, liquid smoke, maple syrup and apple cider vinegar.
4. Add the coconut to the bowl and gently stir to coat it with the soy sauce mixture, being careful not to crush the coconut flakes.
5. Spread the coconut in an even layer on parchment. Drizzle any excess liquid over the coconut.
6. Bake for about 15 minutes, tossing every 3-5 minutes during cooking, until crispy and browned. Watch the coconut closely during baking, because this stuff can go from crispy to char in a very short time.
7. Remove the baking sheet from oven and allow to cool. The coconut bacon will continue to crisp up as it cools.
