#+TITLE: Creamy Potato and Leek Soup
#+DATE: 2021-03-21
#+SETUPFILE: recipe.setup

[[https://lovingitvegan.com/vegan-potato-leek-soup/][Original link]]

* Ingredients
- 1 Onion (Chopped)
- 1 tsp Crushed Garlic
- 1 Tbsp Olive Oil
- 4 Large Leeks (white and light green parts only, chopped)
- 1 tsp Dried Thyme
- 1 tsp Dried Rosemary
- 1/2 tsp Coriander Powder
- 6 Medium Potatoes (~1kg) – peeled and chopped
- 2 Bay Leaves
- 4 Cups Vegetable Stock/Broth
- 400ml Can Coconut Cream
- Sea Salt and Black Pepper (to taste)
- Fresh Chives (Chopped)

* Instructions
1. Add the chopped onion and leeks to a pot with the crushed garlic and olive oil and sauté until softened. Add in the thyme, rosemary and coriander powder and sauté.
2. Add the chopped potatoes, bay leaves and vegetable stock and bring to a boil. Reduce the heat, cover the pot and simmer until the potatoes are soft and cooked.
3. Remove from the heat and remove the bay leaves.
4. Then add in the coconut cream.
5. Blend the soup using an immersion blender for the easiest blending or, if you don’t have an immersion blender, transfer in stages to a blender jug and blend until smooth.
6. Add sea salt and black pepper to taste.
    Serve with fresh chopped chives.
