#+TITLE: Creamy Pasta Soup
#+DATE: 2019-05-28
#+SETUPFILE: recipe.setup

[[https://elavegan.com/creamy-pasta-soup-recipe/][Original link]]

* Ingredients
** For the soup:
   - 1 large (225 g) carrot, peeled and chopped
   - 1-2 stalks (75 g) celery, chopped
   - 200 g broccoli florets
   - 1/2 tbsp oil
   - 1 medium onion, diced
   - 4 garlic cloves, minced
   - 5-6 cups vegetable broth
   - 2 tsp onion powder
   - 2 tsp Italian seasoning
   - 1-2 tsp ground lovage (or to taste)
   - salt and pepper to taste
   - 200 g pasta
   - Fresh herbs to garnish

** Cashew-Cannellini Cream:
   - One can cannellini beans
   - 1/2 cup (75 g) cashews soaked
   - 1 1/2 cups plant-based milk
   - 1 tbsp lemon juice
   - 1/4 tsp salt

* Method
  1. Soak cashews for a couple of hours OR boil them for 20 minutes in water until they are soft. Once the cashews are soft, transfer them to a blender, add the cannellini beans, the plant-based milk, lemon juice & salt and blend on high speed for about 2 minutes or until super smooth and creamy. Set aside.
  1. For the soup: Heat oil in a large pot over medium heat, add the onion, all veggies and fry for about 4 minutes. Then add the garlic, the spices and fry for a further minute.
  1. Add in the veggie broth (I first used 5 cups but had to add another cup later). Bring to a boil and then reduce the heat.
  1. Now add the cashew-cannellini cream and stir. Let the soup simmer for about 6-8 minutes.
  1. Finally, add pasta of choice and let the soup simmer for about 8-10 minutes or until the pasta is al-dente (check the package instructions). Stir frequently! If the soup is too thick either add more veggie broth or plant-based milk! Taste and adjust seasoning. You will most likely need to add more salt!
  1. Garnish with fresh herbs and enjoy!

* Notes
  For a nut-free version, simply use 75 grams of hemp seeds!
