#+TITLE: Creamy Ramen
#+DATE: 2022-07-24
#+SETUPFILE: recipe.setup

[[https://www.youtube.com/watch?v=9E66VTQjhgA][Original link - Yeung Man Cooking]]

* Ingredients
- 1/2 cup coconut cream
- 100g extra firm tofu
- 3 fresh shiitake mushrooms
- 60g broccolini
- 1 tsp cane sugar
- 1 tsp toasted sesame oil
- 2 tbsp [[file:homemade-chilli-oil.org][ chilli oil]]
- 1 1/2 tbsp + 1 tsp soy sauce
- 1 tbsp white sesame paste
- 140g ramen noodles
- 2 1/2 cups veggie stock
- 2 tbsp avocado oil
- 2 tsp dark soy sauce
- chili threads to garnish

* Instructions
1. Bring a pot of water to boil for the noodles
2. Scoop out the coconut cream from the can and set it aside
3. Mash the tofu into a crumble with a fork. Finely chop the shiitake mushrooms and broccolini
4. In the ramen bowl, whisk together the cane sugar, a splash of toasted sesame oil, 1 tbsp chili oil, 1 1/2 tbsp soy sauce, and the white sesame paste
5. When the water comes to a boil, cook the noodles to package instructions. Stir the noodles occasionally
6. Strain out the noodles and set aside. Toss the noodles with a splash of toasted sesame oil
7. Whisk together the veggie stock and coconut cream in a pot heating on medium high heat
8. Heat up a nonstick pan to medium heat. Add in the avocado oil
9. Saute the tofu for 2-3min. Then add the broccolini and mushrooms and saute for another 2-3min
10. Add 1 tsp soy sauce and 2 tsp dark soy sauce. Saute for another minute
11. When the broth comes to a boil, pour it into the ramen bowl. Place in the noodles followed by the sauteed veggies
12. Garnish with some chili threads and another tbsp of chili oil
