#+TITLE: Crispy Oven Baked Black Bean Tacos
#+DATE: 2023-03-12
#+SETUPFILE: recipe.setup

* Ingredients

- Avocado oil for cooking
- 1/2 medium onion, finely chopped
- 4 cloves garlic, minced or grated
- 1 tsp smoked paprika
- 1/2 tsp ground coriander
- 1/2 tsp dry oregano
- 1/4 tsp dry thyme
- 2, 15oz cans black beans, rinsed and drained
- 2 chipotle peppers from a can packed in adobo sauce, minced
- 1/2 cup vegetable broth
- 8-10 corn tortillas
- Salt and pepper to taste Lime wedges for serving
- Avocado slices or Cilantro Lime Sauce (on the blog) for serving

* Method

1. Preheat oven to 425F. To a large rimmed baking sheet, drizzle about 2 tablespoons of oil and brush to evenly coat.
1. Heat up a medium sized sauté pan over medium heat and add 1 tablespoon of oil to the pan to warm through.
1. Add the onions along with a pinch of salt and sauté until softened.
1. Stir in the garlic, sauteing until fragrant.
1. Sprinkle in the seasonings and stir to combine.
1. Add in the black beans and chipotle peppers and continue to sauté for 2-3 minutes.
1. Pour in the veggie broth and lightly mash your beans using the back of a cooking spoon until the mixture starts to bind together then remove from heat. Adjust salt and pepper to taste.
1. Wrap the stack of tortillas in a damp paper towel and microwave for 15-30 seconds to steam them. Take each taco and place on the greased baking sheet, giving a flip to coat both sides in oil. To each tortilla, spread about 2-3 tablespoons of the mashed black beans over half a tortilla and fold it over and flip the taco.
1. Arrange the folded tortillas on the greased baking sheet in a single layer with space between the tacos. Place in the oven to bake for 8 minutes, then carefully flip the tacos and bake for an additional 8-10 minutes until nice and golden.
1. Remove from the oven and allow to cool for 3-5 minutes to allow them to crisp up more and enjoy served with extra lime and salsas of choice.
