#+TITLE: Dan Dan Noodles
#+DATE: 2020-04-26
#+SETUPFILE: recipe.setup

[[https://omnivorescookbook.com/dan-dan-noodles/][Original link]]

* Ingredients
** Noodle sauce
  - 1/3 cup Chinese sesame paste (or unsweetened natural peanut butter)
  - 1/3 cup light soy sauce (or soy sauce)
  - 1/4 cup Chinkiang vinegar
  - 4 cloves garlic, finely minced
  - 2 green onion, finely minced
  - 2 tablespoons honey (or agave syrup)
  - 1/2 to 1 teaspoon Sichuan peppercorns, toasted and grounded

** Garnishes
  - 1/3 cup roasted peanuts, crushed
  - 14 oz (400 g) Dan Dan noodles (or thin wheat noodles)
  - 1 small batch leafy green vegetables, roughly chopped (spinach, choy sum, baby bok choy etc.)
  - (Homemade) chili oil, to taste

* Instructions
  1. Whisk the sesame paste and light soy sauce together in a bowl until fully incorporated. Add the Chinkiang vinegar. Continue stirring until mixed. Then mix in the garlic, green onion, honey, and Sichuan peppercorns.
  2. Cook the noodles according to instructions.
  3. Briefly blanch the leafy green vegetables, drain, and set aside.
  4. For each noodle bowl, add 1/4 cup of noodle sauce. Add the chili oil according to your taste. Add some noodles, then top with green veggies. Garnish with peanut crumbles and chopped green onion. Sprinkle with a pinch of toasted ground Sichuan peppercorn, if you like the numbing taste.
  5. Serve hot or cold.

* Notes
  1. Do add some chili oil even if you prefer not to eat spicy food, because it will add aroma to the sauce and your sauce won’t end up very spicy.
  2. I usually roast the Sichuan peppercorns in a bit of oil until they turn dark brown. Then pat them dry with paper towel and grind them into powder. The oil-roasted peppercorns will be less pungent and have a more rounded flavor. I prefer the cooked peppercorns in cold dishes and sauces so they won’t overpower the other ingredients.
