#+TITLE: Dried tomato pasta bake
#+DATE: 2024-07-15
#+SETUPFILE: recipe.setup

[[https://cupfulofkale.com/vegan-pasta-bake/#mv-creation-152-jtr][Original link]]

* Ingredients
** Pasta Sauce
- 1 red onion
- 4 garlic cloves
- 1 red pepper
- 2 tins (800g total) chopped tomatoes
- 3/4 cup water
- 5 sun dried tomatoes, in oil
- 2 tbsp tomato puree
- 1 tbsp balsamic vinegar
- 1 tsp sugar
- 1 tbsp mixed dried herbs
- Pinch chilli flakes
- 6 vegan sausages

** White Sauce
- 1.5 tbsp vegan butter
- 2 tbsp flour
- 3/4 cup unsweetened almond milk
- 1/2 tsp dijon mustard
- 50g vegan cheddar

** Everything else
- 350g penne pasta
- 1/4 cup vegan cheddar, grated
- 1/4 cup vegan mozzarella, grated

    
* Instructions
1. Pre heat oven to 180\deg{}C.
2. Finely chop the onion and place in a saucepan on medium heat with some oil. Leave to fry for a few minutes.
3. Mince the garlic and finely chop the red pepper and add to the pan. Cook for about 10 minutes until the onion and pepper are soft through.
4. Add the chopped tomatoes, water, finely chopped sun-dried tomatoes, tomato puree, balsamic vinegar, sugar, mixed herbs and pinch chilli flakes (optional). Bring to a gentle simmer and leave to cook for 15-20 minutes. It should have thickened and deepened in colour, add a little more water if you need to whilst cooking.
5. In a separate pan, heat some oil. Cut sausages into small chunks and fry until browned and crispy. Set aside.
6. Make the white sauce. Add vegan butter to a small saucepan on low heat. Once melted add the flour and mix until it forms a roux/paste.
7. Gradually add the milk and whisk continuously until smooth. Add the vegan cheddar and dijon mustard and whisk again until melted and thickened. Set aside.
8. Cook pasta until al dente. Drain and place in an oven proof dish.
9. Taste and season the tomato sauce and pour over the pasta with the cooked sausage. Stir well.
10. Pour the white sauce over the top so it is evenly distributed. Sprinkle the vegan cheddar and mozzarella on top and place in the oven for 20-25 minutes.
11. The cheese should be melted and the sides crispy and bubbling.
12. Serve and top with some fresh basil!
