#+TITLE: Enchilada Bake
#+DATE: 2022-07-24
#+SETUPFILE: recipe.setup

[[https://gamechangersmovie.com/recipes/enchilada-bake-casserole/][Original link - From Game Changers]]

* Ingredients
** Red Enchilada Sauce
- 1 can whole peeled tomatoes
- 1 jar (350g) Roasted Red Peppers, drained
- 1 small can tomato paste
- 1/2 jar (75g) pickled jalapenos
- 1/2 onion, roughly diced
- 1 garlic clove, chopped
- 1 tablespoon cumin
- 1 teaspoon black pepper
- 1/2 teaspoon salt

** Bean and Rice Filling
- 1/2 teaspoon onion, granulated
- 2 cups cooked brown rice
- 2 cans black beans
- 1 cup corn kernels
- 200g bag baby spinach
- 1 teaspoon cumin
- 1/2 teaspoon smoked paprika
- 1/2 teaspoon onion granulated
- 1/2 teaspoon salt

** Sweet Potato Queso
- 2 sweet potatoes, peeled and roughly chopped (roughly 400 g)
- 5 garlic cloves
- 1 bay leaf
- 2 cups unsweetened soy milk or unsweetened plant-based milk
- 1 cup fresh or jar salsa
- 1 tablespoon nutritional yeast (optional)
- 1 teaspoon cumin
- 3/4 teaspoon chili powder
- 1/2 teaspoon smoked paprika
- 1/2 teaspoon salt
- 1/2 teaspoon black pepper

** Other
- 8-10 tortillas (whole wheat or corn)
- Vegetable stock
- 1 teaspoon black pepper
- Classic Sour Cream recipe (optional)
- Hot sauce of choice (optional)


* Method
1. *For the Red Enchilada Sauce*: Heat a medium size saucepan on medium high heat, add the onions and garlic and saute for 1 min. Add the remaining ingredients. Bring to a slow boil, lower the heat to medium-low and cook for 15 minutes, stirring often. Remove from the stove top and let cool. When cool, add the mixture to a blender and blend to chunky-smooth consistency. Set aside.
2. *For the Bean and Rice Filling*: Wilt the baby spinach in a steamer or large saucepan pan by cooking on a medium high heat for 1 minute. Add all ingredients to a large bowl and mix well. Set aside.
3. *For the Sweet Potato Queso*: In small sauce pot, add the first 3 ingredients, add water to cover, and on medium-high heat bring to a boil for 10-12 minutes until the sweet potatoes are soft (can break apart with a fork) and about half the liquid has evaporated. Remove from the stove top and let cool. Remove the bay leaf. Add the cooked sweet potato mixture to a blender, add the seasonings and 1 cup of plant based milk (to start) and blend on low speed moving to high speed for roughly 2 minutes until silky smooth. Add extra plant milk for a thinner sauce and less for thicker. Remember sauce will thicken once cooled or if heated. You can always add more liquid but you cannot take it away, so add the plant milk gradually.
4. For Assembly: (think of building a lasagna, kinda. Have all the components ready to build). Preheat the oven to 180\deg{}C. Warm the tortillas by wrapping in foil and baking in a hot oven for 5 minutes OR put them in the microwave for 1 minute. (Makes easier to wrap). In a large casserole dish, add large ladle of red enchilada sauce as a base. In each tortilla add ¾ cup of the filling and roll. Place each filled tortilla side by each into the casserole dish until the dish is full. Cover the tortillas evenly with Red Enchilada Sauce, drizzle Queso sauce over each roll, cover with tin foil (optional), and bake for 25-30 minutes until hot. Remove the tin foil and bake for an additional 5 minutes. Remove from the oven. Slice down the middle length-wise, scoop to serve or build individual meal prep containers for a few days-worth of meals. Garnish with drizzle of Classic Sour Cream, your favorite hot sauce and fresh coriander. Add more or less salt and pepper to your taste.
