#+TITLE: Focaccia
#+DATE: 2024-05-31
#+SETUPFILE: recipe.setup

[[https://alexandracooks.com/2018/03/02/overnight-refrigerator-focaccia-best-focaccia/][Original link]]

* Ingredients
- 4 cups (512 g) all-purpose flour or bread flour, see notes above
- 2 teaspoons (10 g) kosher salt
- 2 teaspoons (8 g) instant yeast, see notes above if using active dry
- 2 cups (455 g) lukewarm water, made by combining 1/2 cup boiling water with 1 1/2 cups cold water butter for greasing
- 4 tablespoons olive oil, divided flaky sea salt, such as Maldon
- 1 to 2 teaspoons whole rosemary leaves, optional 

* Instructions
1. In a large bowl whisk together flour, salt and instant yeast. Add the water and mix using spatula until all liquid is absorbed. Rub lightly with olive oil and cover with plastic wrap. Let proof in refridgerator for 12 hours to 3 days.
2. Grease a pan with margarine/cooking spray. Pour a tablespoon of olive oil into the center of pan. Release the dough with two forks, form a rough ball and place on tray.
3. Let the dough rest for 3-4 hours at room temperature.
4. Preheat over to 220\deg{}C. Add toppings to dough then with oil coated fingers press deep dimples into the dough. Gently stretch to fill the pan if required. Sprinkle salt.
5. Bake to 25-30 minutes until golden and crisp. Let it cool for 10 minutes before serving.
