#+TITLE: Japanese curry
#+DATE: 2023-08-02
#+SETUPFILE: recipe.setup

[[https://www.okonomikitchen.com/vegan-japanese-curry/#tasty-recipes-13106-jump-target][Original link]]

* Ingredients
** For the Curry

- 1 large (300 g) onion, sliced into wedges
- 2 garlic cloves, grated
- 2 tsp ginger, grated
- ½ (150 g) package mushrooms
- 1 (150 g) carrot, cut into wedges
- 2-3 (250 g) potatoes
- ¾ cup (60 g) soy curls
- ½ (100 g) apple, grated
- 2 ½ cup (625 ml) water
- ½ box (120 g) curry roux cubes (or about 240-270g homemade curry cubes)
- Salt and pepper to taste

** Kakushi aji (hidden flavours)

- ⅓ cup (100 g) caramelized onions (see recipe below)
- 1 tbsp Japanese Worcester or Tonkatsu sauce (15ml)
- 1 tbsp ketchup (15ml)
- 1 tbsp soy sauce (15ml // tamari for gluten free)
- 1 tbsp sugar of choice (14g)
- 1 tsp cocoa powder (3g)
- 1 tsp instant coffee (3g)

** Caramelized onions

- 1 large (300 g) onion
- 1 tbsp (15 g) vegan butter

* Instructions
** Curry

1. Over medium high heat, add onions and fry for 1 minute. Add in garlic and ginger and fry for another minute. Add in the mushrooms, carrots, potatoes and soy curls, and cook for 5 minutes. 
1. Add water and grated apple. Bring to a boil and then reduce heat to a low and simmer for 15 minutes or until you can pierce a toothpick through it. 
1. Turn off the heat. Chop up the roux into small pieces (makes it easier to dissolve). Add the chopped roux to a soup ladle and dissolve it well into the curry. Stir in kakushi aji mixture. Add any other kakushiaji.
1. Turn heat to low and simmer to thicken, about 5 minutes. 
    Serve over rice and enjoy! 

** Caramelized onions

1. Thinly slice the onions. 
1. Heat butter in a medium pan over medium heat until melted. Stir the onions until softened and become translucent.
1. Reduce heat to medium low and continue to cook, stirring every few minutes to prevent them from sticking and burning until light amber (about 20 minutes). Continue to caramelize until golden brown. If at any point it looks like the pan is burning, add a splash of water to deglaze the pan.
1. You can stop here at the point where they are soft and jammy or continue to cook for another 10 minutes until slightly blackened around the edges
