#+TITLE: Lentil + vegan ricotta lasagna
#+DATE: 2024-06-25
#+SETUPFILE: recipe.setup

[[https://www.noracooks.com/best-vegan-lasagna/][Original link]

* Ingredients
- 1 cup dried red lentils
- 2x700 g passata
- 1 cup raw cashews
- 400 g firm tofu patted dry
- 1/2 cup nutritional yeast
- 3 tbsp fresh lemon juice from about 2 lemons
- 1 tsp salt
- 1 tsp dried basil
- 1 tsp oregano
- 1/2 tsp garlic powder
- 3 cups baby spinach
- 1 box lasagna noodles (about 12 noodles)
- (Optional) Vegan Mozzarella Cheese for topping

* Instructions
1. *Cook the red lentils*. Add 1 cup dried red lentils and 3 cups of water to a medium pot. Bring to a boil, and then simmer for about 20 minutes. Drain the lentils in a fine strainer, and then add back to the pot and stir in the marinara sauce. Set aside.
2. Preheat the oven to 180\deg{}C.
3. *Make the Cashew-Tofu Ricotta*. Add the cashews to a food processor and process until fine and crumbly. Then add the tofu in chunks, nutritional yeast, lemon juice, salt, basil, oregano and garlic powder to the food processor. Pulse until well combined and pretty smooth. If it's too thick, add a few tablespoons of water to blend. Set aside.
4. *Assembling the lasagna*. Add about 1 cup of lentil marinara to the bottom of a large casserole dish. Spread it around evenly. Next add 4-5 lasagna noodles (uncooked). Spread half of the ricotta on top of the noodles. Top with half of the spinach. Add about 1 cup of the marinara sauce over the spinach, then place 4-5 lasagna noodles on top. Spread the rest of the ricotta over the noodles, then the rest of the spinach. Place 4-5 more noodles on top of the spinach, and then pour the rest of the sauce over the top, evenly. 
5. Cover tightly with foil and bake for 40 minutes.
6. After 40 minutes, remove the foil and spoon on the mozzarella (or sprinkle the cheese all over). Place the lasagna back in the oven and bake for 20 more minutes, uncovered. Remove from oven, let cool for at least 15 minutes and serve. Leftover lasagna will keep for about 4 days in the refrigerator. See notes for freezing instructions.
