#+TITLE: Mapo tofu
#+DATE: 2021-08-01
#+SETUPFILE: recipe.setup

[[https://madewithlau.com/recipes/mapo-tofu-chicken][Original link]]

* Ingredients
- 500g tofu (any level of firmness is fine)
- 1 tbsp bean sauce 
- 1 tbsp oyster sauce 
- 1/2 tsp dark soy sauce 
- 2 chili peppers (chili sauce also works as a substitute)
- 2 garlic cloves
- 1 green onion (for garnish)
- 1 cup water
- 1 tbsp oil
- 1/2 tsp salt
** Texture
- 1 tsp sesame oil
- 1 tbsp cornstarch
- 2 tbsp water
    
* Instructions
1. Pour the water out of the tofu package, and chop the tofu into cubes.
1. Chop garlic, chilies, and green onion
1. In a bowl, mix together cornstarch (1 tbsp) and water (2 tbsp) until you have an even consistency.
1. Set your stove to its highest setting, and wait a few minutes for your pan or wok to heat up. Once it's hot enough, add oil (1 tbsp), garlic cloves (2), and chilies (2). Stir the garlic and chilies around for 20 to 30 seconds.
1. Add bean sauce (1 tbsp) to the wok, stirring it around with the chicken for about 1 minute. Then, add water (1 cup), sugar, salt (1/2 tsp), oyster sauce (1 tbsp), and dark soy sauce (1/2 tsp). Stir around for a few seconds.
1. Add the tofu to the wok, gently stir it around, and cover the wok with a lid. Let it sit for about 3 minutes, when the wok starts to boil.
1. Slowly pour the cornstarch mix into the wok, gently stirring the wok around as you go. Be careful not to break the tofu in the process. Next, add sesame oil (1 tsp). Gently stir the wok around to mix the sesame oil in.
1. Plate the dish.
