#+TITLE: Oat & Lentil "Meat Loaf"
#+DATE: 2019-12-24
#+SETUPFILE: recipe.setup

[[https://gamechangersmovie.com/recipes/oat-lentil-meat-loaf/][Original link]]

* Ingredients
  - 2 medium carrots, grated
  - 1 zuchinni, grated
  - 1/2 onion, chopped
  - 2 cloves garlic, minced or pressed
  - 300g firm tofu, drained
  - 1/4 cup walnuts, finely ground
  - 1/2 cup cooked brown lentils
  - 1 1/4 cups quick-cooking oats
  - 3 tablespoons soy sauce
  - 2 tablespoons BBQ sauce or ketchup (plus additional for topping)
  - 1 tablespoon Dijon mustard
  - 2 teaspoons dried parsley
  - 1/2 teaspoon thyme
  - 1/2 teaspoon sage
  - 1/2 teaspoon rosemary

* Method
  1. Preheat the oven to 190\deg{}C.
  2. Saute the carrot, zuchinni, onion, and garlic on high heat in a skillet with a few drops of water for 5 minutes, until tender. Remove from heat and cool.
  3. Mash the tofu in a large bowl. Stir in the cooked mixture and remaining ingredients, and combine well.
  4. Spoon the mixture into a parchment-lined loaf pan. Top with a layer of BBQ sauce.
  5. Bake for 55-60 minutes, or until a toothpick inserted in the center comes out clean.

* Tips
  - This meatloaf is wonderful the next day pan-fried on whole grain bread with mustard, pickles, and ketchup.
