#+TITLE: Pizza Dough
#+DATE: 2018-09-08
#+SETUPFILE: recipe.setup

[[https://www.mom4real.com/homemade-pizza-dough-recipe/][Original link]]

* Ingredients
  - 3.5 Cups Bread or All-Purpose Flour
  - 1 Teaspoon Sugar
  - 1 Envelope Instant Dry Yeast
  - 2 Teaspoons Kosher Salt
  - 1.5 Cups Warm Water
  - 2 Tablespoons Olive Oil

* Instructions
  1. Mix together flour, sugar, dry yeast and kosher salt. Slowly add water and olive oil. Mix together until dough forms into a ball. If the dough is too sticky, add a tablespoon of flour until it forms a ball. If the dough is too dry, add a tablespoon of warm water until it forms a ball. Once your dough is formed, knead into a smooth firm ball on a floured surface.
  2. Grease a large bowl with olive oil and place your dough in the bowl. Cover with plastic wrap, and let sit for at least an hour.
  3. The dough will double in size. Now flour your surface and cut the dough in half. Place a damp cloth over the dough and allow it to sit for 10 minutes. Now it's time to roll your dough out into whatever shape you like, while gently pulling the dough to stretch it.

