#+TITLE: Roasted Cauliflower Tacos with Green Tahini Sauce
#+DATE: 2021-07-25
#+SETUPFILE: recipe.setup

* Ingredients

** Tahini sauce

- 1/3 cup tahini
- 1 cup fresh coriander leaves, plus more to serve
- 1/2 clove garlic
- Juice of 1 lemon
- 1 teaspoon ground cumin
- 3/4 teaspoon salt
- 1/4 teaspoon black pepper

** Tacos

- 1 medium cauliflower, chopped into florets
- 2 tablespoons olive oil
- 1 tablespoon cumin
- 1 tablespoon smoked paprika
- 1 teaspoon salt
- 1/2 teaspoon pepper
- 8 tortillas
- purple cabbage, shredded
- 1 avocado, sliced
- 1 chilli, sliced
- 1 lime, cut into wedges

** Pico de Gallo

- Red onion
- Tomato
- Corn
- Avocado
- Lime juice

* Instructions

1. Preheat oven to 180\deg{}C.
2. For TAHINI SAUCE, blend all ingredients in a small food processor or blender until the texture is similar to pesto. Gradually drizzle in 5 tablespoons water and blend until sauce is light green and creamy.
3. FOR TACOS, coat cauliflower with olive oil, cumin, paprika, salt and pepper. Roast for 25 minutes or until golden brown, tossing halfway through.
4. Heat tortillas according to packet instructions.
5. Chop Pico ingredients and mix.
6. TO ASSEMBLE, fill each taco with roasted cauliflower. Top with the cabbage and sliced avocado, and drizzle with the tahini sauce. Garnish with extra coriander, chilli and lime.

* Notes
Tahini sauce and roasted cauliflower can be stored in airtight containers in the fridge for up to 3 days. The tahini sauce can be frozen.

