#+TITLE: Souffle Pancakes
#+DATE: 2024-06-01
#+SETUPFILE: recipe.setup

* Ingredients
** Wet
- 100 mL oat milk
- 100 mL soda water
- 2 tbsp apple-cider vinegar
- 2 tbsp vegetable oil
- 1 tsp vanilla extract

** Dry
- 200 g plain flour
- 50 g icing sugar
- 2 tsp baking powder
- 1/2 tsp bicarb soda

* Instructions
1. Combine all the wet ingredients in a jug and leave to stand for  5 minutes. The mixture will thicken slightly.
2. Sift all the dry ingredients into a medium mixing bowl with a pinch of salt and make a well in the middle. Pour the wet mixture into the dry and, using a spatula, gently fold the dry into the wet, mixing only until there are no visible dry spots.You need to keep the mixture light and airy for this to work.
3. Spray a frying pan with non-stick pray and warm over a low heat for a few minutes. For these pancakes to do the whole souffle thing, they need the assistance of metal ring moulds. The higher the sides the higher you can get your pancakes. Spray the inside of the ring moulds and place into the pan. Fill with 2-3 tbsp of the mixture, depending on how high you'd like them.
4. Once the mix is in and level, place a lid on the pan and allow to cook fro 5 minutes. Remove the lid and flip the pancake while still in the mould.Place the lid back on the pan and cook for another 2 minutes. To test whether they are cooked through, press on the top of a pancake - if there is slight resistance, you should be good to go. Repeat to make remaining pancakes.
5. Top with whatever you damn well please.
