#+TITLE: Tofu Mac N Cheese
#+DATE: 2024-03-13
#+SETUPFILE: recipe.setup

[[https://www.instagram.com/p/C33Av3XPJrh/][Original link]]

* Ingredients
** Macaroni
- 300g macaroni
- 2 heaped tbsp vegan butter/margarine
- 1 heaped tbsp flour
- 500ml unsweetened plant milk
- 1/3 cup (~50g) nutritional yeast
- 300g silken tofu
- 2 tsp apple cider vinegar
- 1 tsp miso paste
- 0.5 tsp turmeric powder
- 0.5 tsp garlic granules
- Salt to taste

** Gochugang Tofu
- 400g super-firm tofu
- 1 heaped tbsp cornflour (cornstarch)
- 1 tbsp sesame oil
- 1 heaped tbsp gochujang
- 2 tbsp light soy
- 2 tbsp maple syrup
- 0.5 tsp garlic granules
- 3 tbsp water
 
* Instructions
** For the mac
1. Cook the macaroni in salted boiling water until al dente.
2. In a saucepan, melt the butter over a medium heat.
3. Add the flour and whisk to combine, then little by little add the milk to make a smooth roux. Gradually keeping adding the milk, whisking to combine.
4. Once all the milk is in, add the remaining ingredients and whisk well to combine. If the sauce is too thick, add some more milk.
5. Season to taste and when you’re happy, stir in the cooked macaroni.

** For the gochujang tofu
1. Rip or chop the tofu into chunks, toss in the cornflour and then toss in the oil.
2. Air fry the tofu for 8-10 minutes at 200&deg;C until crisp - alternatively, you can fry or bake it.
3. Mix the sauce ingredients, add to a frying pan and bring to a simmer.
4. Simmer away for a couple of minutes until it thickens a little and starts to get real sticky then throw the tofu in and coat it in the sauce.

Serve the gochujang tofu with the mac & cheese, top with spring onions, sesame seeds & crispy chilli oil.
