#+TITLE: Vegan Palak Paneer
#+DATE: 2019-08-12
#+SETUPFILE: recipe.setup

[[https://minimalistbaker.com/vegan-palak-paneer-with-curried-tofu/][Original link]]

* Ingredients
** Tofu
   - 1 450g block firm tofu (drained, patted dry, and cubed)
   - 1 1/2 tsp curry powder (or store-bought)
   - 1 Tbsp coconut aminos
   - 1/4 tsp sea salt
   - 2 tsp nutritional yeast (adds a slightly cheesy flavor)

** Spinach
   - 5 cups loosely packed fresh spinach (about 170g)
   - Water

** Vegetables
   - 1 1/2 Tbsp avocado or coconut oil (or sub water + add more as needed)
   - 1 1/2 tsp cumin seed (or ground cumin)
   - 2 Tbsp minced ginger
   - 1 medium diced white onion
   - 1 serrano or jalapeno pepper (seeds removed, diced // add more or less to preferred spiciness)
   - 1 can diced tomatoes (slightly drained // or sub fresh chopped ripe tomatoes)
   - 4 cloves garlic 
   - 1/4-1/2 cup vegetable broth or water

** Sauce
   - 1 1/2 Tbsp avocado or coconut oil (or sub water + add more as needed)
   - 2 tsp curry powder
   - 1 tsp garam masala
   - 1/3 cup full fat coconut milk (plus more for serving)
   -  Sea salt, coconut aminos, or tamari (to taste // we used a few teaspoons of coconut aminos)

** For serving (optional)
   - Rice or Quinoa
   - Cilantro
   - Garlic Naan

* Method
  1. This recipe is all about multi-tasking and is totally doable in 30 minutes.
     Start by preheating the oven to 210°C and draining your tofu. Then wrap in
     a clean towel and set something heavy on top. (This step can also be done
     in advance with a tofu press.)
  2. Cube tofu and add to a medium mixing bowl. Season with curry powder,
     coconut aminos, sea salt, and nutritional yeast. Shake the bowl to gently
     toss. Set aside.
  3. Heat a medium oven-safe seasoned cast iron over medium heat (if using a
     stainless steel skillet, add a little oil so it doesn't stick). Once hot,
     add the tofu and saute for 3-4 minutes, or until a couple of the sides are
     browned. Then transfer to the hot oven and bake for 15 minutes. If you
     prefer firmer tofu, bake longer. If you want softer tofu that mocks paneer,
     bake less. Set aside to rest in the pan.
  4. Fill a large pot halfway full with water and bring to a boil over high
     heat. While you wait, move on to the next step.
  5. Heat a large rimmed skillet over medium heat. Once hot, add oil and cumin
     seed, ginger, onion, and serrano pepper. Saute until onion is soft and
     translucent (about 5 minutes).
  6. Add diced tomatoes and garlic and stir to combine. Saute for 3-4 minutes,
     or until the tomato has softened.
  7. Your water should be boiling now. Add spinach and cook uncovered for 2
     minutes. Then strain and rinse with cold water. Drain well. Set aside.
  8. Add the tomato mixture to a blender or food processor along with cooked
     drained spinach and the vegetable broth (or water). Blend into a smooth
     sauce, scraping down sides as needed. If it has trouble blending, add more
     vegetable broth or water.
  9. Lastly, cook your sauce. Heat the same rimmed skillet from earlier over
     medium heat. Once hot, add remaining oil (or some water), curry powder, and
     garam masala. Stir and cook for 30 seconds.
  10. Add the spinach sauce and stir. Cook the mixture over medium-low heat for
      about 3-4 minutes to deepen the flavors. If it bubbles too much, lower
      heat to a simmer. Then add coconut milk and stir.
  11. Taste and adjust flavor as needed, adding salt or coconut aminos to deepen
      the flavor and curry powder for more rich curry flavor.
  12. Serve over your tofu paneer and garnish with another drizzle of full fat
      coconut milk and fresh cilantro. Rice makes a lovely side, as does garlic
      naan! Store leftovers covered in the refrigerator up to 4-5 days, or in
      the freezer up to 1 month. Reheat in the microwave or in a rimmed skillet
      until hot.
