#+TITLE: Vegan Meatballs with Gravy
#+DATE: 2019-04-09
#+SETUPFILE: recipe.setup

  [[https://elavegan.com/vegan-meatballs-gravy-gluten-free-recipe/][Original link]]

* Ingredients
** Vegan meatballs:
    - One 400 g can black beans , drained and rinsed (250 g)
    - 1/4 cup sunflower seeds (35 g)
    - 1/2 cup oats (gluten-free if needed) (45 g)
    - 2 tbsp tomato paste (60 g)
    - 2 cloves of garlic
    - 1/2 large onion, chopped
    - 2 tbsp ground chia seeds or flax seeds
    - Spice mix: 1/2 tbsp onion powder, 1 tsp garlic powder, 1 tsp ground
    - oregano, 1 tsp ground cumin, 1/2 tsp smoked paprika, 1/4 tsp red pepper
    - flakes
    - Sea salt and pepper to taste
    - Oil for frying

** Mashed taters:
    - 6 medium-sized potatoes
    - 1/4 cup coconut milk canned (60 ml) (*see recipe notes)
    - 1/2 tsp nutmeg (or more/less to taste)
    - black pepper, sea salt to taste

** Gravy:
    - 1 1/2 cups vegetable broth or water (360 ml)
    - 1/3 cup plant-based cream or canned coconut milk (80 ml)
    - 2 tbsp tomato paste (60 g)
    - 1/2 tsp fresh ginger (minced)
    - Ground spice mix: 3 tsp curry powder, 1 1/2 tsp onion powder, 1 tsp
    - garlic powder, 1 tsp oregano, 1 tsp cumin, 1 tsp turmeric, 1/2 tsp
    - nutmeg, 1/2 tsp smoked paprika, 1/4 tsp red pepper flakes, 1 tsp coconut
    - sugar (or brown sugar), sea salt and pepper to taste
    - 1 tbsp cornstarch (to thicken)
    - Fresh parsley to garnish

* Method
   1. Preheat oven to 200\deg{}C.
   2. Prepare mashed potatoes as described in this recipe or make your favorite pasta or rice (whatever you want to serve with your vegan meatballs).

** Meatballs:
    1. Put all ingredients (except oil) to a food processor or blender and pulse a couple of times. Scrape down the sides and pulse again. Repeat for about one minute or until the mixture sticks together.
    2. Roll the mixture with your hands into balls. I used 1 tbsp per ball (the recipe makes about 15 balls).
    3. Heat 2-3 tbsp oil in a pan/skillet and fry balls for about 6-8 minutes over medium heat. Shake the pan from time to time to fry the balls evenly from all sides.
    4. Transfer the balls to a baking sheet and bake in the oven for about 20 minutes.

** Mashed taters:
    1. Peel and chop potatoes, transfer them to a pot with salted water and bring to a boil.
    2. Cook on medium heat for about 15 minutes or until tender, drain.
    3. Transfer back to the pot, add coconut milk, nutmeg, black pepper and sea salt to taste and mash with a potato masher (don't use a food processor or blender).

** Gravy:
    1. To make the gravy, simply add the tomato paste to a pan (use the same pan which you used for the vegan meatballs), pour in the plant-based cream and stir with a whisk to smooth out the tomato paste. Then slowly add the vegetable broth while stirring.
    2. Bring the sauce to a boil, add all other ingredients (except cornstarch and fresh parsley) and let simmer over medium heat for about 10-12 minutes (the longer you simmer the gravy, the more flavorful and thicker it will be).
    3. In a small bowl mix cornstarch with a little bit of water and add it to the pan. The gravy will get a little bit thicker. Keep simmering for a further 2-3 minutes.
    4. Pour the gravy over the vegan meatballs and serve with either mashed potatoes, pasta or rice! Store leftovers of the gravy in a container in the fridge (can be kept in the fridge for about 3-4 days).

