#+TITLE: Vegetarian Chili
#+DATE: 2019-05-28
#+SETUPFILE: recipe.setup

[[https://cookieandkate.com/vegetarian-chili-recipe/][Original link]]

* Ingredients
  - 2 tablespoons extra-virgin olive oil
  - 1 medium red onion, chopped
  - 1 large red bell pepper, chopped
  - 2 medium carrots, chopped
  - 2 ribs celery, chopped
  - 1/2 teaspoon salt, divided
  - 4 cloves garlic, pressed or minced
  - 2 tablespoons chili powder*
  - 2 teaspoons ground cumin
  - 1 1/2 teaspoons smoked paprika*
  - 1 teaspoon dried oregano
  - 2 cans (800 g) diced tomatoes, with their juices
  - 2 cans (800 g) black beans, rinsed and drained
  - 1 can (400 g) pinto beans, rinsed and drained
  - 2 cups vegetable broth or water
  - 1 bay leaf
  - 2 tablespoons chopped fresh cilantro, plus more for garnishing
  - 1 to 2 teaspoons sherry vinegar or red wine vinegar or lime juice, to taste
  - Garnishes: chopped cilantro, sliced avocado, tortilla chips, etc.

* Instructions
  1. In a large Dutch oven or heavy-bottomed pot over medium heat, warm the olive oil until shimmering. Add the chopped onion, bell pepper, carrot, celery and 1/4 teaspoon of the salt. Stir to combine and cook, stirring occasionally, until the vegetables are tender and the onion is translucent, about 7 to 10 minutes.
  1. Add the garlic, chili powder, cumin, smoked paprika and oregano. Cook until fragrant while stirring constantly, about 1 minute.
  1. Add the diced tomatoes and their juices, the drained black beans and pinto beans, vegetable broth and bay leaf. Stir to combine and let the mixture come to a simmer. Continue cooking, stirring occasionally and reducing heat as necessary to maintain a gentle simmer, for 30 minutes.
  1. Remove the chili from the heat.
  1. For the best texture and flavor, transfer 1 1/2 cups of the chili to a blender, making sure to get some of the liquid portion. Securely fasten the lid and blend until smooth (watch out for hot steam), then pour the blended mixture back into the pot. (Or, you can blend the chili briefly with an immersion blender, or mash the chili with a potato masher until it reaches a thicker, more chili-like consistency.)
  1. Add the chopped cilantro, stir to blend, and then mix in the vinegar, to taste. Add salt to taste, too---I added 1/4 teaspoon more at this point.
  1. Divide the mixture into individual bowls and serve with garnishes of your choice. This chili will keep well in the refrigerator for about 4 days or you can freeze it for longer-term storage.
