#+TITLE: Wellington Loaf
#+DATE: 2024-12-29
#+SETUPFILE: recipe.setup

[[https://veganhuggs.com/vegan-wellington/][Original link]]

* Ingredients
- 1 sheet vegan puff pastry , thawed if frozen (about 10X13)
- 2 tblsp ground flax meal + 5 tblsp water
- 2 tblsp grapeseed oil , or preferred cooking oil
- 1/2 medium onion , diced
- 2 small carrots , diced small
- 2 stalks celery , diced
- 4 cloves garlic , minced or crushed
- 1 tsp dried thyme
- 1 tsp ground sage
- 1/2 tsp dried rosemary
- 8 ounces mushrooms , minced or finely chopped
- 1.5 tblsp tamari sauce , low sodium (sub soy sauce)
- 1 15 oz can chickpeas (garbanzo beans) , drained well but NOT rinsed
- 3/4 cup unsalted walnuts , ground into a course meal (measured whole)
- 1/2 cup panko breadcrumbs , more if needed
- 2 tblsp tomato paste
- 1.5 tblsp vegan worcestershire sauce
- 1/2 tsp salt , more to taste
- Fresh cracked pepper , to taste
- 1 tablespoon vegan butter , melted

* Instructions
1. Preheat oven to 200\deg{}C. Line a rimmed baking sheet with parchment paper and set aside. 
2. Combine the ground flax and water in a small bowl. Set aside for 10 min. It will thicken and gel up a bit. 
3. Heat oil in a large skillet over medium heat. Now add onion, celery, and carrots. Sauté until softened about 6-8 minutes.
4. Add garlic, thyme, sage, and rosemary. Sauté for 1 minute.
5. Add mushrooms and sauté until they soften and release their moisture about 5-7 minutes. You want the pan to be dry. Now add the tamari and cook for 1 minute. Remove from heat and set aside to cool for 10 minutes.
6. Add chickpeas to a large mixing bowl and mash with a potato masher. Don't over mash - just mash enough to break down whole chickpeas, but leave lots of texture. 
7. Now add the cooled mixture, breadcrumbs, walnut meal, flax mixture, Worcestershire, tomato paste, salt, and pepper. Combine well with a spatula and use your hands if needed. Taste and add more seasoning if preferred. (If the mixture seems too wet, you can add another ¼ cup of breadcrumbs or rolled oats - You should be able to form it with your hands easily) 
8. Using your hands, shape the mixture into a solid log that will fit in the middle of the pastry sheet (with a few inches of slack). Make sure log is packed well. 
9. Unroll puff pastry sheet and lay it over the baking sheet (or a flat surface if you need to roll it first). Place the loaf in the middle of the pastry sheet. Pick up one side and wrap it over the loaf and repeat on the other side. Gently press to seal together (don't force if it doesn't close, just thin & lengthen the loaf or remove some mixture and form again). *If pastry doesn't seal easily, just lightly brush a little non-dairy milk in that area and seal.
10. Now roll up the ends and press gently to seal. If you have a lot of extra length, you may want to trim the dough first before sealing. Otherwise, the ends of the loaf will be very doughy. Flip the loaf over so the sealed edges are facing the baking sheet. 
11. Brush the top and sides with melted vegan butter. Using a sharp knife, gently make diagonal slits across the whole top of loaf about 1-inch apart. Now repeat going the other direction to criss-cross slits (see process photos in post above). 
12. Place in the oven for 30-35 minutes until heated throughout and the pastry is golden brown. Let sit 10 minutes before gently cutting with a sharp knife. I felt it was easiest to cut into the slits that were made earlier. Serve with Gravy if desired. Enjoy! 
