#+TITLE: West African Peanut Soup
#+DATE: 2018-05-14
#+SETUPFILE: recipe.setup

[[http://cookieandkate.com/2013/west-african-peanut-soup/][Original link]]

* Ingredients
  - 6 cups low sodium vegetable broth
  - 1 medium red onion, chopped
  - 2 tablespoons peeled and minced fresh ginger
  - 4 cloves garlic, minced
  - 1 teaspoon salt
  - 1 bunch collard greens (or kale), ribs removed and leaves chopped into 1-inch strips
  - 0.75 cup unsalted peanut butter (chunky or smooth)
  - 0.5 cup tomato paste*
  - Hot sauce, like sriracha (AKA rooster sauce)
  - 0.25 cup roughly chopped peanuts, for garnish

* Method
  1. In a medium Dutch oven or stock pot, bring the broth to a boil. Add the onion, ginger, garlic and salt. Cook on medium-low heat for 20 minutes.
  2. In a medium-sized, heat-safe mixing bowl, combine the peanut butter and tomato paste, then transfer 1 to 2 cups of the hot stock to the bowl. Whisk the mixture together until smooth, then pour the peanut mixture back into the soup and mix well. Stir in the collard greens and season the soup with hot sauce to taste.
  3. Simmer for about 15 more minutes on medium-low heat, stirring often. Serve over cooked brown rice if you'd like, and top with a sprinkle of chopped peanuts.
