#+TITLE: White sauce pasta bake
#+DATE: 2026-01-26
#+SETUPFILE: recipe.setup

[[https://lovingitvegan.com/vegan-pasta-bake/#recipe][Original link]]

* Ingredients
** Pasta
- 450g Penne Pasta (dry weight)

** For the Bolognese Sauce:
- 1 Medium Onion White, Yellow or Brown, Chopped
- 1 teaspoon Crushed Garlic
- 1 Tablespoon Olive Oil
- 5 cups White Button Mushrooms (480g) Sliced
- 1 Tablespoon Soy Sauce
- 1/2 cup Tomato Paste (130g)
- 1 can Brown Lentils (400mL) or 1.5 cups cooked brown lentils
- 2 cans Canned Chopped Tomato (800g)
- 1-2 Tablespoons Light Brown Sugar
- Salt and Pepper to taste

** Cashew Cream
- 1 cup Raw Cashews (150g)
- 1 Tablespoon Lemon Juice
- 1/2 cup Water (120mL)
- 1/2 teaspoon Salt

** White Sauce
- 3 Tablespoons Vegan Butter
- 2 Tablespoons All Purpose Flour
- 1 can Coconut Milk (400mL) Full Fat, Canned, Unsweetened
- 1/3 cup Vegetable Stock (80mL) or Broth
- 1 teaspoon Black Pepper
- 1 teaspoon Dijon Mustard
- 1/4 cup Nutritional Yeast (15g)
- Sea Salt to taste

* Instructions
1. Put the pasta on to cook while you prepare the vegetables for the bolognese sauce. When the pasta is cooked, drain it, cover it (to prevent it from drying out) and set aside.
2. Prepare your bolognese sauce. Add the onion and garlic to a pot with the olive oil and fry until softened. Then add in the sliced mushrooms and soy sauce. Cover the pot for a minute and allow the mushrooms to release their water. Then remove the lid from the pot and let the water from the mushrooms cook off a little. Add in the tomato paste, lentils and chopped tomato. Bring to a simmer. Add the sugar to balance out the flavors and add salt and pepper to taste.
3. Prepare your cashew cream. Add the cashews, lemon juice, water and salt to the blender jug and blend until smooth.
4. Add the cashew cream to your bolognese sauce and mix it in. Then add your pasta and mix it all in together.
5. Now prepare your white sauce. Add the vegan butter to a saucepan and let it melt and start to sizzle just a little. Add in the flour and stir it quickly, then add in the coconut milk and vegetable stock and whisk it very quickly to get rid of the lumps. Then switch to a wooden spoon and keep stirring while you bring it to the boil. Once it boils keep stirring for about another 4 minutes until thickened. Then remove from heat and add in the black pepper, dijon mustard, nutritional yeast and sea salt.
6. Preheat the oven to 220\deg{}C.
7. Place the pasta and bolognese mix into a rectangular oven-safe dish and smooth down.
8. Pour the white sauce over the top and smooth down.
9. Bake uncovered for 20 minutes until golden on top.
