#+TITLE: Aussie Damper
#+DATE: 2018-05-14
#+SETUPFILE: ../recipe.setup

[[https://foodequalshappyme.com/2013/01/13/aussie-damper/][Original link]]

* Ingredients:
  - 3 cups self raising flour
  - Pinch of salt
  - 80g chilled butter
  - 3/4 cup of water

* Instructions
  1. Sift flour and salt in a bowl. Cut the chilled butter into cubes and rub into the flour with your fingertips until the mixture looks like breadcrumbs.
  2. Make a well in the center and add the water. Using a butter knife in a cutting motion mix until the mixture comes together. If it looks a little dry you can add a little extra water.
  3. Turn the mixture out onto a floured surface, and pull it together with your hands. Knead it gently for 1-2mins or until it becomes smooth. Shape it into a round and using a knife dipped in flour, lightly mark 8 wedges on the top.
  4. Place it on a baking tray lined with baking paper. Sprinkle the top with flour, and bake for 35mins at 200\deg{}C, or until golden and when tapped underneath sounds hollow.
  5. Leave it to cool on a wire rack for 30mins. If you cut it too soon it will look undercooked, however it just needs time to rest before cutting.

