#+TITLE: Classic Italian Bread
#+DATE: 2018-05-14
#+SETUPFILE: ../recipe.setup

[[http://www.girlversusdough.com/2014/09/18/classic-italian-bread/][Original link]]

* Ingredients
  - 2 1/4 teaspoons (1 packet) Red Star active dry yeast
  - 1 teaspoon granulated sugar
  - 1 cup warm water (about 45\deg{}C)
  - 2 1/2 cups bread or all-purpose flour
  - 2 tablespoons olive oil
  - 1 teaspoon salt

* Instructions
  1. In a large bowl or bowl of a stand mixer, combine yeast, sugar and warm water. Let stand 5 minutes until yeast is foamy.
  2. Add 2 cups flour, olive oil and salt. Stir with a wooden spoon or with a dough hook on low speed until a shaggy dough forms. Turn dough out onto a lightly floured surface and knead by hand 10 minutes, adding just enough of the remaining flour until a soft, smooth and elastic dough forms; OR, increase dough hook speed to medium and knead dough in stand mixer 5 minutes, adding just enough of the remaining flour until a soft, smooth and elastic dough forms.
  3. Shape dough into a ball; place in an oiled bowl and turn to coat. Cover bowl with plastic wrap and let dough rise 1 hour until doubled.
  4. Heat oven to 400 degrees F. Line a baking sheet with a silicone mat or lightly grease the surface with oil or cooking spray. On a lightly floured surface, punch down dough, then carefully shape into a batard/torpedo about 12 inches long. Transfer to prepared baking sheet. Cover with a tea towel and let rise another 20 minutes until puffy.
  5. Use a serrated knife to make a few ¼-inch deep slits in the surface of the loaf. Bake loaf 20 minutes until golden brown. Cool completely on a cooling rack before slicing.

