#+TITLE: Coconut Curry Lentil Soup
#+DATE: 2018-08-03
#+SETUPFILE: ../recipe.setup

[[http://vegangela.com/2014/01/09/coconut-curry-lentil-soup/][Original link]]

* Ingredients
  - 1 tbsp coconut oil (or olive oil)
  - 1 large onion, chopped
  - 2 cloves garlic, minced
  - 1 tbsp fresh ginger, minced
  - 2 tbsp tomato paste (or ketchup)
  - 2 tbsp curry powder
  - ½ tsp hot red pepper flakes
  - 4 cups vegetable broth
  - 1 400ml can coconut milk
  - 1 400g can diced tomatoes
  - 1.5 cups dry red lentils
  - 2-3 handfuls of chopped kale or spinach
  - salt and pepper, to taste
  - Garnish: chopped cilantro (fresh coriander) and/or vegan sour cream

* Instructions
  1. In a stockpot, heat the coconut oil over medium heat and stir-fry the onion, garlic and ginger until the onion is translucent, a couple minutes.
  2. Add the tomato paste (or ketchup), curry powder, and red pepper flakes and cook for another minute.
  3. Add the vegetable broth, coconut milk, diced tomatoes and lentils. Cover and bring to a boil, then simmer on low heat for 20-30 minutes, until the lentils are very tender. Season with salt and pepper.
  4. {Make-Ahead: May be cooled, frozen in air-tight containers, and re-heated over medium-low heat.}
  5. Before serving, stir in the kale/spinach and garnish with cilantro and/or vegan sour cream.

