#+TITLE: Mediterranean Baked Sweet Potatoes
#+DATE: 2018-05-14
#+SETUPFILE: ../recipe.setup

[[https://minimalistbaker.com/mediterranean-baked-sweet-potatoes/][Original link]]

* Ingredients
  - 4 medium sweet potatoes* (~140 g each)
  - 1 can (400 g) chickpeas, rinsed and drained
  - 1/2 Tbsp olive oil
  - 1/2 tsp each cumin, coriander, cinnamon, smoked (or regular) paprika
  - optional: Pinch of sea salt or lemon juice

** Garlic herb sauce
   - 1/4 cup (60 g) hummus (or tahini)
   - juice of 1/2 lemon (~1 Tbsp)
   - 3/4 - 1 tsp dried dill (or sub 2-3 tsp fresh)
   - 3 cloves garlic, minced (1 1/2 Tbsp or 9 g)
   - Water or unsweetened almond milk to thin
   - optional: Sea salt to taste (I didn't need any)

** Toppings
   - 1/4 cup (45 g) cherry tomatoes, diced
   - 1/4 cup (15 g) chopped parsley, minced
   - 2 Tbsp (30 ml) lemon juice
   - Chili garlic sauce

* Instructions
  1. Preheat oven to 400 degrees and line a large baking sheet with foil.
  2. Rinse and scrub potatoes and cut in half length wise. This will speed cooking time. Otherwise leave whole and bake longer (approximately double the time (45 min - 1 hour).
  3. Toss rinsed and drained chickpeas with olive oil and spices and place on a foil-lined baking sheet.
  4. Rub the sweet potatoes with a bit of olive oil and place face down on the same baking sheet (or another baking sheet depending on size).
  5. While the sweet potatoes and chickpeas are roasting, prepare your sauce by adding all ingredients to a mixing bowl and whisking to combine, only adding enough water to almond milk to thin so it's pourable. Taste and adjust seasonings as needed. Add more garlic for more zing, salt for savoriness, lemon juice for freshness, and dill for a more intense herb flavor. I found mine didn't need anything else.
  6. NOTE: If you don't have hummus, tahini will make a great base substitute for the sauce - just adjust the seasonings to accommodate the lack of flavor tahini provides.
  7. Also prepare the parsley-tomato topping by tossing tomato and parsley with lemon juice and setting aside to marinate.
  8. Once sweet potatoes are fork tender and the chickpeas are golden brown - roughly 25 minutes - remove from oven.
  9. For serving, flip potatoes flesh-side up and smash down the insides a little bit. Then top with chickpeas, sauce and parsley-tomato garnish. Serve immediately.
  10. Additional side ideas might include Hummus, Pita Chips, Baba Ganoush, or Persian Eggplant Dip. Enjoy!

