#+TITLE: Oil-Free Hummus
#+DATE: 2019-10-02
#+SETUPFILE: ../recipe.setup

[[https://elavegan.com/oil-free-hummus/][Original link]]

* Ingredients
  - One can chickpeas
  - 1/4 cup (60 g) tahini
  - 4 tbsp (40 ml) lemon juice (or more to taste)
  - 1/3 tsp salt or more to taste
  - 1/4 tsp ground cumin
  - 4 tbsp (40 ml) plant-based milk (or more for a creamier hummus)
  - 2-3 small cloves of garlic
  - 1/3 tsp baking soda
  - Paprika for serving
  - Fresh parsley for serving

* Instructions
  1. Rinse and drain canned chickpeas, then place in a medium saucepan and add 1/3 tsp baking soda. Cover chickpeas by at least 2 inches (ca. 5 cm) of water and bring to a boil over high heat. See recipe notes if you want to cook the chickpeas from dry.
  2. Boil the chickpeas for about 15 minutes. Once they look overcooked and slightly mushy, they are ready! Drain the chickpeas in a strainer, rinse with plenty of cool water and set aside.
  3. Process the lemon juice, garlic, salt, cumin, half of the plant-based milk, and tahini in a food processor until the mixture is smooth and creamy. Pause the food processor to scrape down the sides of the processor.
  4. Add the mushy chickpeas to the food processor and blend for about 1-2 minutes, scraping down the sides of the processor as needed.
  5. Now add the remaining plant-based milk and blend for a further 1-2 minutes, or until very smooth, creamy and fluffy.
  6. Taste the hummus and add more salt to taste and more lemon juice, if desired.
  7. Serve in a bowl and top with more lemon juice (I also added a bit of the chickpea cooking water), a dash of paprika (use smoked paprika for a variation), and fresh herbs.
  8. Store leftover hummus covered in the refrigerator for up to 5-6 days.

* Notes
  - If you don't want to use canned chickpeas you can cook them from dry. Here is how:
  - In a medium bowl, cover 3/4 cup (150 grams) dried chickpeas by at least 5 cm of cold water.
  - Add 1/2 tsp baking soda and let soak at room temperature overnight. Drain and rinse.
  - In a medium pot, cover soaked chickpeas by about 10 cm of water.
  - Add 1/2 tsp baking soda and bring to a boil over high heat.
  - Reduce the heat and simmer until chickpeas are soft, about 1 1/2 hours.
  - Drain and rinse under running water.
  - Recipe serves 6. 
