#+TITLE: Roast Carrot Lentil Curry Bowls
#+DATE: 2018-06-12
#+SETUPFILE: ../recipe.setup

  [[http://pinchofyum.com/lentil-curry-bowls-with-cilantro-cashew-sauce ][Original link]]

* Ingredients
** For the Cilantro Cashew Sauce:
    - 1/2 cup fresh cilantro
    - 3/4 cup cashews (mine were salted)
    - ? cup water
    - 1/4 teaspoon salt
    - juice of 2 limes
    - 1 clove garlic (optional)
    - 1-2 teaspoons honey

** For the Roasted Carrots:
    - 8-10 carrots, peeled and chopped into chunks
    - 1 tablespoon olive oil
    - 1 teaspoon garam masala
    - 1/2 teaspoon chili powder
    - salt to taste

** For the Rice and Lentil Curry:
    - 1 cup basmati rice
    - 1 tablespoon oil
    - 1/2 cup chopped onion
    - 2 cloves garlic
    - 2 tablespoons red Thai curry paste
    - 1 teaspoon garam masala
    - 1/2 teaspoon cumin seed (or ground cumin)
    - 1 cup brown lentils, rinsed
    - 400 g tomato puree (passata)
    - 2 cups chicken or vegetable broth
    - pinch of salt
    - avocado and cilantro for topping

* Instructions
   1. For the sauce, puree all ingredients in a food processor or blender until smooth. Taste and adjust.
   2. For the carrots, toss all ingredients together. Roast at 450 degrees for 20-30 minutes or until golden brown and roasty. <-- favorite word.
   3. Cook the rice according to package directions. I used a rice cooker.
   4. For the curry, heat the oil in a skillet over medium heat. Add the onion and garlic; saute for 3-5 minutes. Add the curry paste and spices; saute for 2-3 minutes.
   5. Add the lentils, tomato sauce, and broth. Simmer until lots of the liquid has evaporated - continue adding ½ cup of liquid as needed (the lentils will just keep soaking it up). Repeat this process for about 30-45 minutes until the lentils are soft.
   6. Add the rice to the lentil mixture; stir to combine, adding extra broth or water as necessary. Season with salt.
   7. Serve in bowls topped with the roasted carrots, avocado slices, cilantro, and cilantro cashew dressing.

