#+TITLE: Spicy Buddha Bowl
#+DATE: 2018-05-14
#+SETUPFILE: ../recipe.setup

  [[http://www.crazyvegankitchen.com/spicy-buddha-bowl/][Original link]]

* Ingredients
   - 1 cup Cooked Brown Rice
   - 1 Sweet Potato, cut into large chunks
   - 1 teaspoon Olive Oil
   - Salt/Pepper
   - 1 can Organic Chickpeas, drained
   - 1 1/2 tablespoons Sriracha
   - 2 teaspoons Maple Syrup
   - 1/2 teaspoon Paprika
   - 1/2 teaspoon Garlic Powder
   - Salt/Pepper
   - 1 cup chopped Red Cabbage
   - 1 cup Baby Spinach
   - 1 Avocado, sliced
   - Turmeric Tahini Dressing:
   - 4 Tablespoons Tahini
   - 4 Tablespoons Warm Water
   - 1 teaspoon Maple Syrup
   - 1/4 teaspoon Cayenne Pepper
   - 1/2 teaspoon Turmeric
   - 1/2 teaspoon Sriracha
   - Salt to taste

* Instructions
   1. Preheat oven to 180 degrees Celsius. Coat sweet potato in 1 tsp oil and season with salt and pepper. Place on baking tray and pop into the oven to roast for 35 minutes, turning once halfway through the cooking time.
   2. Whilst sweet potato is cooking, prepare chickpeas.
   3. In a bowl, combine chickpeas, sriracha, maple syrup, paprika, garlic powder, salt and pepper. Mix to combine. Heat a saucepan and transfer chickpea mixture into saucepan to cook for 5-10 minutes. Make sure to keep the chickpeas moving so they don't burn. Cook until chickpeas are slightly sticky and no longer watery. Keep aside.
   4. In a clean saucepan, wilt spinach slightly and season. Transfer to a bowl and repeat the wilting and seasoning process with the cabbage.
   5. Once sweet potato is cooked through, prepare your Buddha Bowl by placing your rice in the bottom of a bowl and then topping with the sweet potato, chickpeas, spinach, red cabbage and avocado.
   6. To make dressing, whisk all ingredients together. Liberally splash on Buddha Bowl and enjoy!!!

