#+TITLE: Sweet Potato Chickpea Buddha Bowl
#+DATE: 2018-05-14
#+SETUPFILE: ../recipe.setup

  [[https://minimalistbaker.com/sweet-potato-chickpea-buddha-bowl/][Original link]]

* Ingredients
   - 2 Tbsp olive, melted coconut, or grape seed oil
   - 1/2 red onion, sliced in wedges
   - 2 large sweet potatoes, halved
   - 1 bundle (227 g) broccolini, large stems removed, chopped
   - 2 big handfuls kale, larger stems removed
   - 1/4 tsp each salt + pepper

** Chickpeas
    - 1 can (400 g) chickpeas, drained, rinsed + patted dry
    - 1 tsp cumin
    - 3/4 tsp chili powder
    - 3/4 tsp garlic powder
    - 1/4 tsp each salt + pepper
    - 1/2 tsp oregano (optional)
    - 2/4 tsp turmeric (optional)

** Tahini sauce (optional)
    - 1/4 cup (56 g) tahini
    - 1 Tbsp maple syrup
    - 1/2 lemon, juiced
    - 2-4 Tbsp hot water to thin

* Instructions
   1. Preheat oven to 400 degrees F and arrange sweet potatoes and onions on a bare baking sheet. Drizzle both with a bit of oil, making sure the flesh of the sweet potatoes are well coated and placed skin side down on the sheet.
   2. Bake for 10 minutes, then remove from oven flip sweet potatoes and add broccolini. Drizzle broccolini with a bit of oil and season with a pinch each salt and pepper.
   3. Bake for another 8-10 minutes, then remove from oven and add kale. Drizzle kale with a touch more oil and season with a pinch each salt and pepper. Bake for another 4-5 minutes then set aside.
   4. While vegetables are roasting, heat a large skillet over medium heat and add chickpeas to a mixing bowl and toss with seasonings.
   5. Once hot, add 1 Tbsp oil and chickpeas and sauté, stirring frequently. If they're browning too quickly, turn down heat. If there isn't much browning going on, increase heat. I found 10 minutes total at slightly over medium heat was perfect.
   6. Once the chickpeas are browned and fragrant, remove from heat and set aside.
   7. Prepare sauce by adding tahini, maple syrup and lemon juice to a mixing bowl and whisking to combine. Add hot water until a pourable sauce is formed. Set aside.
   8. To serve: Slice sweet potatoes into bite size pieces. Divide vegetables between 3 serving bowls and top with chickpeas + tahini sauce.
   8. Best when fresh, though leftovers will keep for a few days in the fridge.

