#+TITLE: Tan Tan Noodles
#+DATE: 2020-07-02
#+SETUPFILE: ../recipe.setup

[[https://www.youtube.com/watch?v=2DnezXrRVAQ][Original link]]

This recipe will make a single serving.

* Ingredients
** Noodles
   - drizzle of olive oil
   - 1/4 cup canned sliced bamboo
   - 1/4 cup corn
   - fresh cracked pepper
   - 1/4 cup dried wild mushrooms (rehydrated)
   - pinch of pink salt
   - 1 bundle of dried ramen noodles
   - 2 cups veggie stock
   - 5g kombu
   - 1 tbsp white sesame paste (Chinese style or tahini)
   - 1 tsp sesame oil
   - 1 tsp rice vinegar
   - 1 tbsp soy sauce
   - 1 tsp cane sugar
   - 1 tsp + 1 tbsp chili oil (https://youtu.be/DUDKIcYltZA)
   - 1/4 cup cashew milk (canned coconut milk will work too!)
   - 1 stick green onion
** Garnishes
   - 1 tbsp korean dried chili pepper threads
   - 1 [[file:./cashew-ramen-egg.org][cashew ramen egg]] 

* Instructions
  1. Bring a pot of water to boil for the noodles. In the meantime, heat up a sauté pan on medium high heat and add a drizzle of olive oil
  2. Sauté the bamboo for a few minutes. Add the corn and sauté for another minute. Then, set aside
  3. Mince the rehydrated wild mushrooms and sauté with a pinch of pink salt for 2-3min. Then, set aside
  4. Cook the noodles in boiling water to package instructions and loosen the noodles with chopsticks occasionally
  5. Heat up the veggie stock and kombu in the sauté pan (or in a stock pot if multiplying the recipe)
  6. Add the sesame paste, sesame oil, rice vinegar, soy sauce, cane sugar, and 1 tsp chili oil to your serving bowl. Whisk to combine
  7. When the broth comes to a boil, remove the kombu. Turn the heat off. When the broth is no longer boiling, add the cashew milk in while whisking
  8. Pour the broth into the serving bowl. Strain out the cooked noodles and add to the bowl
  9. Top the ramen with the bamboo, corn, wild mushrooms, fresh chopped green onion, Korean dried chili pepper threads, cashew ramen egg, and 1 tbsp chili oil
